### ISSUE TITLE
Data request

### ISSUE THREAD

**Issue by susantiyuni** [CederGroupHub/text-mined-synthesis_public#1]
Hey,

Thanks for the great project. 
Is it possible to share the original data, I mean not the automatically generated data (the json one) but the original text used for learning. 
In the shared json data, there is this paragraph_string but only include the 50 first and last characters of the original text data. Is it possible to get this full paragraph text data?

Again, thank you very much for the great effort.

**Comment by OlgaGKononova** [comment]
Hi, @littleflow3r 
thank you for you interest in the dataset.
Unfortunately, according to the Text and Data Mining Agreement with publishers we are not permitted to share any text beyond ~100-150 characters, therefore only those are available to identify the paragraph in the paper text.

**Comment by susantiyuni** [comment]
I see. Thanks!

**Comment by susantiyuni** [comment]
Hi again!
In the paper you mentioned 
`We manually annotated 834 solid-state synthesis paragraphs from 750 papers by assigning each word token with the following tags: “material”, “target”, “precursor”, and “outside” (not a material entity). `
I just want to confirm, is it also not possible to share the annotated data used for that (materials entity recognition)?

Thank you!

**Comment by OlgaGKononova** [comment]
@littleflow3r 
unfortunately not. The annotated text is still a complete paragraph which is protected by publishers copyrights.

**Comment by susantiyuni** [comment]
Thanks!
