### ISSUE TITLE
MER install problem

### ISSUE THREAD

**Issue by CNGaoWenbo** [CederGroupHub/text-mined-synthesis_public#2]
Hi, there is an error when I install Materials Entity Recognition (MER), using 'git clone git@github.com:CederGroupHub/MatEntityRecognition.git'

ERROR: Repository not found.
fatal: Could not read from remote repository.

do you have any idea? 
Thanks!

**Comment by OlgaGKononova** [comment]
Hi, @CNGaoWenbo,
The problem was that the link follows to a private repo.
I have updated the link to the current one.
