### ISSUE TITLE
The full corpus is not provided?

### ISSUE THREAD

**Issue by bowdbeg** [CederGroupHub/text-mined-synthesis_public#4]
Hi,
I would like to use your corpus to challenge the extraction of the recipes. However, when I checked the contents of the json files (extracted from solid-state_dataset_2019-12-03.json.xz and solid-state_dataset_20200713.json.xz), the text of the paragraph is omitted, as shown below in "**<...>**".

Is the full dataset published?

```json
    {"token": "repelleted", "type": "ShapingOperation", "conditions": null}],
  "paragraph_string": "All materials were obtained from Aldrich Chemicals<...>d repelleted after each 24 or 48 h heating period."
},
```

**Comment by hhaoyan** [comment]
Hi @bowdbeg our text-mining agreements with publishers grant us rights to mine the data but not to distribute the original works. So unfortunately the full `paragraph_string` cannot be published. Please let us know if anything else looks interesting to you and we are happy to share them.

**Comment by bowdbeg** [comment]
Thank you very much for your answer, @hhaoyan . I understand that the text cannot be published.
